name: Bridge main to prod

on:
  push:
    branches:
      - main

jobs:
  bridge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create merge commit
      run: |
        git checkout prod
        git merge --no-ff main -m "Merge branch 'main' into prod"

    - name: Push changes
      run: |
        git push origin prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
