name: Deploy on sf_db changes

on:
  push:
    branches:
      - main
    paths:
      - 'sf_db/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # 사용하는 Node.js 버전

    - name: Install dependencies
      run: npm install

    - name: Deploy to server
      run: pm2 deploy db.config.js production

    - name: Reload PM2
      run: pm2 reload db.config.js --env production
